### ISSUE TITLE
bootstrap not installing properly

### ISSUE THREAD

**Issue by nwilcox11** [ga-wdi-boston/game-project#14]
ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
Module parse failed: /Users/nickwilcox/wdi/projects/js-template/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4172-4253 6:4276-4357

I am getting the same error that James was getting.  I followed the installation protocol.

**Comment by GA-MEB** [comment]
Are you using any glyphicons in your page?

**Comment by gaand** [comment]
This seems like #5

**Comment by nwilcox11** [comment]
No I am not using any glyphicons

**Comment by RealWeeks** [comment]
@nwilcox11 In agreement with @gaand. Troubleshoot this yesterday, was quickly resolved.

**Comment by jrhorn424** [comment]
The problem is that the loaders for fonts and other static assets were added to `js-template`. The reason I added them there instead of the bootstrap talk is because whether or not you use bootstrap, it's a good idea to have loaders defined for fonts and svgs.

The solution:
-   [ ] From the project repository, add `js-template` as a remote
-   [ ] Fetch the new remote
-   [ ] Check out the latest versions of grunt configuration and package.json, for example `git checkout js-template/master -- grunt package.json`
-   [ ] `npm install`
-   [ ] `grunt serve` to test
-   [ ] Commit these new files (and only these new files) with a meaningful message
