### ISSUE TITLE
change password ajax

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#141]
having issues with change password

ncaught Error: Cannot find module "./auth/events.js"webpackMissingModule @ index.js:9(anonymous function) @ index.js:9(anonymous function) @ bundle.js:346__webpack_require__ @ bootstrap fc5b826…:50(anonymous function) @ index.js:8__webpack_require__ @ bootstrap fc5b826…:50webpackJsonpCallback @ bootstrap fc5b826…:21(anonymous function) @ bundle.js:1

**Comment by RealWeeks** [comment]
You've have a few errors like this.  These are easy to solve on your own, or at least you could dig deeper into the the issue and have a more thorough question.  This error provides a line number and file `index.js:9` and tells you what the problem is `Cannot find module "./auth/events.js"`.  Please use your abilities to try to figure out your own errors first then be more specific with your questions when you get stuck.
