### ISSUE TITLE
Bootstrap not installing properply (Different error msg)

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/game-project#15]
Everything seems correct but when I post this code:
- $icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
- @import '~bootstrap-sass/assets/stylesheets/bootstrap';

into my style manifest, i get the following error message:

ERROR in ./~/css-loader!./~/sass-loader!./assets/styles/index.scss
Module build failed: 
- $icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
  ^
    Invalid CSS after "": expected 1 selector or at-rule, was "con-font-path: ..."
    in /home/jeremiah/wdi/projects/temp2/tictactoe/assets/styles/index.scss (line 1, column 1)
  @ ./assets/styles/index.scss 4:14-122

Any idea why? I did npm install and I have bootstrap 3.3.6 in my webpack.js file.

**Comment by RealWeeks** [comment]
Similar to issue #14 and #5

**Comment by jrhorn424** [comment]
The problem is that the loaders for fonts and other static assets were added to `js-template`. The reason I added them there instead of the bootstrap talk is because whether or not you use bootstrap, it's a good idea to have loaders defined for fonts and svgs.

The solution:
-   [ ] From the project repository, add `js-template` as a remote
-   [ ] Fetch the new remote
-   [ ] Check out the latest versions of grunt configuration and package.json, for example `git checkout js-template/master -- grunt package.json`
-   [ ] `npm install`
-   [ ] `grunt serve` to test
-   [ ] Commit these new files (and only these new files) with a meaningful message
