### ISSUE TITLE
Installing bootstrap on my current project

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/game-project#18]
`ERROR in ./~/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
Module parse failed: /Users/kevinpie/wdi/projects/tic-tac/ticky-tacky/node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <?xml version="1.0" standalone="no"?>
| <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
| <svg xmlns="http://www.w3.org/2000/svg">
 @ ./~/css-loader!./~/sass-loader!./assets/styles/index.scss 6:4756-4837`

**Comment by jrhorn424** [comment]
The problem is that the loaders for fonts and other static assets were added to `js-template`. The reason I added them there instead of the bootstrap talk is because whether or not you use bootstrap, it's a good idea to have loaders defined for fonts and svgs.

The solution:
-   [ ] From the project repository, add `js-template` as a remote
-   [ ] Fetch the new remote
-   [ ] Check out the latest versions of grunt configuration and package.json, for example `git checkout js-template/master -- grunt package.json`
-   [ ] `npm install`
-   [ ] `grunt serve` to test
-   [ ] Commit these new files (and only these new files) with a meaningful message
