### ISSUE TITLE
Can't get my buttons to link

### ISSUE THREAD

**Issue by viohlet** [ga-wdi-boston/game-project#268]
Hello - I am in need of help to understand my functions and which of them go in various directories. This is a bad issue set-up but hoping to get orientation. Also working on my tic tac toe with buttons and do not know how to link data-id to js. I have tried making it a function but I overlap others. I will meet with Julie 2:15... hoping you can see me today.
Thank you

**Comment by laurenfazah** [comment]
This looks like it might be two separate issues. Let's focus on one here and open up a second issue if appropriate. 

If you want to talk about your functions, can you post examples of what you have set up and what is not working or what you need more clarity with? 

Otherwise, if you want to talk about tic-tac-toe buttons...can you show what you've put as your data-id in HTML as well as post the JS you've used to try to get those values.

**Comment by jrhorn424** [comment]
You can attach the `data-id` when you render the string into your DOM. See something like this: https://github.com/ga-wdi-boston/jquery-todo-challenge/blob/draft-solution/assets/scripts/app/render.js#L13

And @laurenfazah is correct, this is two separate issues. Please open a different issue for "where to place functions in files". However, the general guidance will be to follow the code for books in the `jquery-ajax-*` lessons.

**Comment by viohlet** [comment]
Thank you for the kind reply. Please see below my code for one of the buttons in html:
`<input value=" " data-id="0" name=b00 class="tile" type="button" style="font-size:18pt;height:160px;width:160px">`html

In my gameLogic.js file, I inserted an empty array but not sure how it can contain <forms> with the data-id tag.
`let boardArray = [" ", " ", " ", " ", " ", " ", " ", " ", " "];
`js

I've also tried but when I insert data-id I get an error about data/id not being defined.
`const setGame = function(){
        // empty board
        boardArray = [];
        boardArray[0] = " ";
        boardArray[1] = " ";
        boardArray[2] = " ";
        boardArray[3] = " ";
        boardArray[4] = " ";
        boardArray[5] = " ";
        boardArray[6] = " ";
        boardArray[7] = " ";
        boardArray[8] = " ";`js

Thank you for your guidance.

**Comment by laurenfazah** [comment]
So that button with `data-id="0"` would be placed at index 0 of the `boardArray`, yes?

If you were able to grab 0 from `data-id`, could you then push the value of X or O to the right index of `boardArray`?

Seems like you should first try to use jQuery to get the value of `data-id`: https://api.jquery.com/data/#data2

Then, see if you can push that value into the `boardArray` at the correct index.

**Comment by jrhorn424** [comment]
@laurenallegra May be able to help with this @viohlet. She just did something similar to @laurenfazah's suggestion with her own game board.

**Comment by jrhorn424** [comment]
I highly recommend looking at the examples in the jquery documentation that @laurenfazah linked to as well. It shows how to use `data-id` or `data-<anything>` to store things you need later.

**Comment by jrhorn424** [comment]
No updates?

**Comment by viohlet** [comment]
Hi Jeff - decided to go with a regular grid because unfortunately, I could not figure it out. Will try tomorrow if I have available time. Thank you for the reminder.
