### ISSUE TITLE
JS - Deployment issue with bundle.js and var api

### ISSUE THREAD

**Issue by kiraamaa** [ga-wdi-boston/game-project#373]
I have tried 3-4 times to deploy and have been rejected each time. I finally ran a successful grunt build, but unable to git push origin gh-pages after adding and committing the bundle.js file. I'm now seeing 

```js
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git push origin gh-pages
To github.com:kiraamaa/tic-tac-toe-project.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:kiraamaa/tic-tac-toe-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/tic-tac-toe-project (gh-pages)$ 
```

**Comment by kiraamaa** [comment]
I don't want to do a git pull without instruction.

**Comment by neugierige** [comment]
did you add and commit the bundle.js file from a different branch? 

I think it's fine to do `git pull origin gh-pages`. It will just pull in and incorporate the changes you previously committed.

**Comment by gaand** [comment]
The gh-pages branch doesn't need to be maintained, but it's strange that it's out of sync with your local repository.  Did you edit any files directly on GitHub?

You can run `git push origin gh-pages --force` to overwrite the remote gh-pages branch with the local branch.

Only use this on the `gh-pages` branch, and only after getting a rejection message as above.  Never do a force push if you don't know why it's necessary/what it might destroy.

**Comment by kiraamaa** [comment]
I removed my original gh-pages branch locally and remotely via the terminal but then made a new branch to begin the deployment process anew. Would that cause all of this?

**Comment by BenGitsCode** [comment]
what would cause what? The discrepancy in your gh-pages branch?

**Comment by kiraamaa** [comment]
I'm not sure. I didn't think I had a discrepancy since I started from scratch. I could delete and remake the branch again. After issuing the pull request I still get this

``` js
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git pull origin gh-pages
From github.com:kiraamaa/tic-tac-toe-project
 * branch            gh-pages   -> FETCH_HEAD
First, rewinding head to replay your work on top of it...
Applying: Trying to deploy again
Applying: Deployment attempt
Using index info to reconstruct a base tree...
.git/rebase-apply/patch:663: trailing whitespace.
    /*
.git/rebase-apply/patch:664: trailing whitespace.
        MIT License http://www.opensource.org/licenses/mit-license.php
.git/rebase-apply/patch:665: trailing whitespace.
        Author Tobias Koppers @sokra
.git/rebase-apply/patch:666: trailing whitespace.
    */
.git/rebase-apply/patch:667: trailing whitespace.
    // css base code, injected by the css-loader
warning: squelched 291 whitespace errors
warning: 296 lines add whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging bundle.js
CONFLICT (add/add): Merge conflict in bundle.js
error: Failed to merge in the changes.
Patch failed at 0002 Deployment attempt
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

Should i try Antony's suggested command `js git push origin gh-pages force` ?

**Comment by kiraamaa** [comment]
Everything works on my local branch, and I don't understand why this is happening. Would it be better to come in early tomorrow to fix this?

**Comment by BenGitsCode** [comment]
Does your local branch meet the requirements?

**Comment by raq929** [comment]
I suspect you did not successfully delete the remote branch. Ben will be in early, and should be able to get you sorted.

**Comment by kiraamaa** [comment]
Yes, my local branch meets requirements.

**Comment by kiraamaa** [comment]
Yes, I figured that may have been the case although I tried to use the most forceful deletes possible. I'll be in early to figure it out. I'm heading to bed but thank you!

**Comment by kiraamaa** [comment]
Should I close this yet?

**Comment by BenGitsCode** [comment]
Leave it open, and close it with the solution tomorrow.

**Comment by kiraamaa** [comment]
Okay, thanks

**Comment by jdaly04** [comment]
I have the same issue where terminal message is:
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git push origin gh-pages
To github.com:jdaly04/tic-tac-toe-project.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:jdaly04/tic-tac-toe-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git push origin gh-pages
To github.com:jdaly04/tic-tac-toe-project.git
 ! [rejected]        gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:jdaly04/tic-tac-toe-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/tic-tac-toe-project (gh-pages)$

**Comment by jdaly04** [comment]
`````` html
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git push origin gh-pages
To github.com:jdaly04/tic-tac-toe-project.git
! [rejected] gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:jdaly04/tic-tac-toe-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/tic-tac-toe-project (gh-pages)$ git push origin gh-pages
To github.com:jdaly04/tic-tac-toe-project.git
! [rejected] gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'git@github.com:jdaly04/tic-tac-toe-project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~/wdi/projects/tic-tac-toe-project (gh-pages)$

```html
``````

**Comment by BenGitsCode** [comment]
@jdaly04 I'll go over this fix in the morning.

**Comment by BenGitsCode** [comment]
@jdaly04 I'll go over this fix in the morning.

**Comment by BenGitsCode** [comment]
@jdaly04 I'll go over this fix in the morning.

**Comment by BenGitsCode** [comment]
@jdaly04 I'll go over this fix in the morning.

**Comment by BenGitsCode** [comment]
@jdaly04 I'll go over this fix in the morning.

**Comment by kiraamaa** [comment]
solved this today with @BenGitsCode. thanks!
