### ISSUE TITLE
trouble with curl request

### ISSUE THREAD

**Issue by dsweetser** [ga-wdi-boston/game-project#427]
Hey Team!

I'm trying to get a better feel of what's going with the server side game functions by playing around with curl commands.  I can do the basic sign up, log in, change password stuff, but I'm having trouble accessing the tic-tac-toe specific parts.  I've tried a variety of commands, my most recent being attempting to create a game with the following: 

```sh
# edited by @jrhorn424 - please format your code blocks in the future!
curl "http://tic-tac-toe.wdibos.com/1569/games/" \
  --include \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Athorization: Token token=${token-id}" \
  --data '{
  "game": {
    "id": 1,
    "cells": ["","","","","","","","",""],
    "over": false,
    "player_x": {
      "id": 1569,
      "email": "grumpy"
    },
    "player_o": null
  }
}'
```

(${token-id} is my login token)

and I get an error 404 Not found.  

being thorough, the same request with the url:
"http://tic-tac-toe.wdibos.com/games/" which gives 401 Unauthorized

and "http://tic-tac-toe.wdibos.com/games/1569" which also gives 404 Not Found

I'm not sure how to proceed!

**Comment by jrhorn424** [comment]
I need to see how you're calling the script. Or are you just doing this in the terminal? If the latter, I'm not sure how you're setting the token.

Additionally, does `${token-id}` match the format from our scripts? I wouldn't trust dashes in the terminal, and terminal variables usually have different casing rules than what your example uses.

`404`s are usually due to a URL-VERB combination that the server doesn't understand (and I can confirm that this is the case in your first example).

`401` indicates the token was wrong (or maybe even absent).

Lastly, inspect the data you're sending. Is it possible to create a game and specify its ID as it is being created? Is the game's ID something we should have control over?

**Comment by dsweetser** [comment]
I'm calling the script in terminal.

a more precise token line is: --header "Authorization: Token token=c7a09afb25bb15db3fd7f92507433f67" - you're right on the data line, it should be blank.

**Comment by jrhorn424** [comment]
I see it now. You have a typo, specifically, a misspelling. See if you can spot it.

**Comment by dsweetser** [comment]
[expletive deleted]
