### ISSUE TITLE
Requesting a 1 on 1 for understanding AJAX

### ISSUE THREAD

**Issue by jwaskow** [ga-wdi-boston/game-project#430]
I'm working on the AJAX game actions but I'm quite confused as to how AJAX works.  I have my sign-up, sign-in, change-password, and sign-out actions working, but only because we did those in the lessons and I had the code available.  I still don't fully understand what is going on.  I re-read all the AJAX documentation repo's but they don't go into much detail or explanation.  I read the MDN documentation on AJAX and it went over my head.  Could I meet with someone this afternoon to discuss what AJAX is and how it interacts with JSON and the API?  It isn't clear to me how data is stored on the server and how we use requests to access it.  I'm going to grab lunch now, but I should be back in 30-45 minutes.  Thanks.

**Comment by bernardlee** [comment]
What about Ajax specifically do you want to know about?  Can you give us some details as to which part(s) of the documentation that you found the most confusing?

**Comment by jwaskow** [comment]
Honestly I find the general syntax confusing and it's hard for me to know what the code is supposed to be doing.  From what we did in the lessons, the events.js file is most confusing to me.  I don't understand how data is taken from the user input and then processed and sent to the server stored as JSON.  It would help me a lot if I could talk through the functions with someone so I can understand what each part does.

**Comment by jwaskow** [comment]
I'm also confused on the project requirements for AJAX, specifically the update action.  How do we save an unfinished game?  When we load the unfinished game, is the game state supposed to show on the game board?

Also how do we store 2 users in the JSON when only one user is logged in?

**Comment by jwaskow** [comment]
Is it possible I can talk with someone in person?  I've been working on this for the past 2 hours and have made little progress.

**Comment by bernardlee** [comment]
We provided a file, `lib/get-form-fields.js`, that essentially traverses a `<form>`, gets all of its inputs (text, checkboxes, radio buttons, etc.), puts all of the information into an object, and returns it.  Some of the functions in `events.js` use it to get form field data (such as an id) to send to the API.

`api.js` is where the calls to jQuery's `.ajax()` method occurs and we're just telling it the path, verb, and, if applicable, the data payload (passed into the functions in `api.js` as arguments from `events.js`).  These responses are `Promise`s (we'll get into them later on) and it's why we chain can `.then()` and `.catch()` to them.

**Comment by jrhorn424** [comment]
@jwaskow I'll chime in shortly. I'm putting together a longer response.

**Comment by jrhorn424** [comment]
> I'm working on the AJAX game actions but I'm quite confused as to how AJAX works.

Does that mean you're uncomfortable, or that you can't do an AJAX request?

> I still don't fully understand what is going on. 

That's OK, and normal.

> Could I meet with someone this afternoon to discuss what AJAX is and how it interacts with JSON and the API?

AJAX is just `curl`, but for your webapp. It asks for data from the API with an HTTP request, and it comes back from the API as an HTTP response with the body being JSON. I recommend reviewing `http-study` and `json-study` if you're curious.

>  It isn't clear to me how data is stored on the server and how we use requests to access it. 

That's not really your concern right now. We'll be diving into it in the next unit. Requests are straight-forward: they're made up of some headers, a URL, and a verb. That triggers some code to run on the server, and the output of that code is (eventually) a JSON response (sometimes).

> Honestly I find the general syntax confusing and it's hard for me to know what the code is supposed to be doing. 

`$.ajax` is a function. When it executes, it makes an HTTP request for you. How do you tell `curl` what VERB and URL and data to use? You use flags. How do you tell `ajax` what to do? You pass it an object literal that has all these "arguments" as key-value pairs. When the response comes back from the server, it will trigger whatever code is in `then`, which is likely in a different file (`events.js`). Don't worry about the mechanics of `ajax` or `then`. You just need to be able to use it to get data.

> From what we did in the lessons, the events.js file is most confusing to me. I don't understand how data is taken from the user input and then processed and sent to the server stored as JSON. 

As @bernardlee mentioned, we "serialize" the data out of the forms, which produces a JavaScript object (**not** JSON; how are they different?). The keys in that object match the value of the name attribute in the inputs of our form. When we pass it in, it's just like writing JSON in a `curl` script. `jQuery.ajax` turns that object into a JSON string and sends it as part of the web request.

> It would help me a lot if I could talk through the functions with someone so I can understand what each part does.

Do you mean the `get-form-fields` code? I hesitate to spend time on this. If you really think it would be valuable, I'll do that.

> I'm also confused on the project requirements for AJAX, specifically the update action. 

Update just changes part of the game board array already stored on the server (adding an "x" or an "o").

> How do we save an unfinished game? 

Every time you update, you're saving the game. :smile:

> When we load the unfinished game, is the game state supposed to show on the game board?

I'm not certain that's a requirement. If it is, we should remove it. It's definitely within your ability to do so (we've introduced you to all the tools you need), but since it isn't critical, I'd save that feature for later.

> Also how do we store 2 users in the JSON when only one user is logged in?

You don't. `player_o` is only used if you work on the multiplayer (cross-device) feature.

@jwaskow I'd be happy to discuss this further now that we've covered a bit of ground. Thanks for being patient!

**Comment by jwaskow** [comment]
Thank you for this, it helped quite a bit.  I've started to make more progress on this, so I'll close this issue for now.  The update function is still confusing, specifically turning the game state data into JSON and sending it to the api, but Ill work on that and open another issue if I need help.
