### ISSUE TITLE
overwhelmed

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#433]
I'm looking for guidance in how to debug when there are so many bugs..
do you look for the root of the problem? what if there are multiple and you don't even know? and you don't understand grunt nag's messages?
I feel stuck because I don't know where to continue. When i debug something more problems arise which makes it feel like whatever i do there is no end.

**Comment by jrhorn424** [comment]
> I feel stuck because I don't know where to continue. When i debug something more problems arise which makes it feel like whatever i do there is no end.

This is normal.

The reason you're dealing with this is because you wrote too much code without testing it. That's also normal at this stage, but it's something you should be wary of as you continue.

We say to be methodical, but we also try to demonstrate it. Have you noticed how we rarely write more than a few lines of code without checking our understanding of how it works?

> I'm looking for guidance in how to debug when there are so many bugs..

I'm not saying this to dismiss you or belittle your overwhelm. The way you debug is "one at a time". Work slowly. Think critically about the things you are writing.

Most importantly, keep it up.

Another really good strategy is to open issues about specific bugs. That's what we're here for: to help you.

**Comment by doremaxime** [comment]
thank you
