### ISSUE TITLE
Grunt nag maximum line length

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/game-project#456]
Hi, I was checking in `grunt nag` and got the error for I hit the maximum line limit... I tried the backslash + enter trick, but atom wouldn't let me do that. Is there a way to go around that, or should I be condensing my line?
```node
  } else if (winnerIs(player[0] === false && winnerIs(player[1] === false && tieGame() === false))) {
```
(for the record, I tried switching it to just say `else`, but then my program didn't recognize that the game was over.)

**Comment by MicFin** [comment]
Thank you for asking.  I believe this is an instance where it would be ok to have a longer line than we have told the linter we prefer to have.

Often times you can use a function or nested conditions to refactor so that the condition in the if statement is not as long.

Check out https://softwareengineering.stackexchange.com/questions/3450/most-readable-way-to-format-long-if-conditions

**Comment by laurpaik-zz** [comment]
Thank you!
