### ISSUE TITLE
1 on 1 request

### ISSUE THREAD

**Issue by cob0910** [ga-wdi-boston/game-project#458]
I believe I am close to finishing my game (I have written the get/post/patch code but haven't been able to connect it to the game board yet) and would like to review what I have with someone before the weekend.

**Comment by MicFin** [comment]
Did you deploy on github pages?  Share the url and I will play your game!

**Comment by bernardlee** [comment]
Sure.

**Comment by cob0910** [comment]
https://github.com/cathyob/tic-tac-toe/tree/master

**Comment by MicFin** [comment]
So fun!! I won!!  I was able to play multiple games in a row too!

Some items to look at:
1.  Sign Out: I could not sign out after signing up, however it did work after signing in 
2.  Change password: did work but it was hard to test because I could not sign out after sign up, I had to refresh and sign in
3.  Game list: the game list never displayed my games, only a message saying games would be displayed there

Awesome job!! See if you can tackle these bugs.  The first step is trying to reproduce the bugs on your own.
