### ISSUE TITLE
Unsure of what I am supposed to do with AJAX get functions

### ISSUE THREAD

**Issue by d00medman** [ga-wdi-boston/game-project#653]
So I have both the AJAX get functions up and running. However, I am not exactly sure what I am supposed to do w/them from here. 

What do my get functions need to do in the application? Is my understanding (that they simply need to return their data) correct?

**Comment by jordanallain** [comment]
not just return, but display the data to the user.

**Comment by d00medman** [comment]
Does it have to look nice? Or can it just be the raw data?

**Comment by tvcrawley** [comment]
To answer that, please revisit the [requirements](https://github.com/ga-wdi-boston/game-project/blob/master/requirements.md), specifically the **your app must not** section.

**Comment by BenGitsCode** [comment]
@d00medman Look at it  this way:

rendering something like `you have played x games of tic tac toe` is great. That is displaying game statistics to the user.  

but if you had it so that the user clicking a `get stats` button rendered the following:
```
{
  "games": [
    {
      "id": 1,
      "cells": ["o","x","o","x","o","x","o","x","o"],
      "over": true,
      "player_x": {
        "id": 1,
        "email": "and@and.com"
      },
      "player_o": {
        "id": 3,
        "email": "dna@dna.com"
      }
    },
    {
      "id": 2,
      "cells": ["","","","","","","","",""],
      "over": false,
      "player_x": {
        "id": 3,
        "email": "dna@dna.com"
      },
      "player_o": {
        "id": 1,
        "email": "and@and.com"
      }
    }
  ]
}
```

Do you understand my point? It doesn't need to be pretty, but it does need to be something reasonably understood by the user, users don't know JSON.

**Comment by d00medman** [comment]
Yeah that was the idea I came away with

**Comment by BenGitsCode** [comment]
Awesome, just wanted to make sure! 👍
