### ISSUE TITLE
Index.scss issue - Several linter errors whenever the index.scss file is used

### ISSUE THREAD

**Issue by CoreyFedde** [ga-wdi-boston/game-project#768]
Linter Output:
"Error running scss-lint: See Console for more info. (Open View -> Developer -> Toggle Developer Tools)"

Issue Description:

Issue first appeared the first time I typed anything in the scss file.

Error message is as follows:"Error running scss-lint: See Console for more info. (Open View -> Developer -> Toggle Developer Tools)"

No specific code caused the issue, it is any input.

I've talked with Chris and deleted the scss-lint.yml file, but the error messages persist.

The errors have been appearing since the beginning.

**Comment by cpearce31** [comment]
Please close since we resolved this. For anyone else running into this issue: delete `.scss-lint.yml` and go to `packages -> settings view -> manage packages`, search for `scss-lint`, and disable it. Restart Atom, then go to `index.scss`, type some invalid CSS, and make sure that your linter is still giving you warnings.
