### ISSUE TITLE
'user' not recognized

### ISSUE THREAD

**Issue by jingrid** [ga-wdi-boston/game-project#796]
I'm testing my sign out button and I keep getting the following error logging in my console:
```
TypeError: Cannot read property 'user' of undefined
    at Object.signOutSuccess (ui.js:35)
    at mightThrow (jquery.js:3583)
    at process (jquery.js:3651)
```

This is what I have in my ui.js file:
```
const signOutSuccess = (data) => {
  store.user = data.user
  console.log(store.user)
  console.log('successfully signed out')
}
```
My api.js file:
```
const signOut = function (data) {
  return $.ajax({
    url: app.host + '/sign-out/' + store.user.id,
    method: 'DELETE',
    headers: {
      Authorization: 'Token token=' + store.user.token
    },
    data
  })
}
```
Not sure how I can get 'user' to be defined

**Comment by jordanallain** [comment]
are you storing a user after sign in succeeds?

**Comment by scottyscripts** [comment]
So it looks like whatever you are calling user on is undefined. What do you get when you `console.log(data)`? Remember that `data` in your `signOutSuccess` function is representing what you get back from the server. Does a call to sign-out usually return data?

**Comment by jingrid** [comment]
Ohhhhh so console.log(data) prints out `undefined` because the method in api.js is DELETE? Got rid of 'data' from the params of signOutSuccess and got rid of store.user = data.user and now it seems to be working.

**Comment by scottyscripts** [comment]
signOutSuccess is being passed whatever is returned from the API for that request. Whether data is sent back during requests is completely up to who is building the API. In this case, `data` is undefined because nothing is returned by the API when we make a request to `/sign-out`. However when we make a request to `/sign-in` for example we get a user object back, so in that case, data would represent that object returned from the server.
