### ISSUE TITLE
Capture win totals

### ISSUE THREAD

**Issue by jbculbertson** [ga-wdi-boston/game-project#825]
When I run GET index on a user, I get back an object (data), which contains an array called Games.  That array contains objects for each game.  How can I get win totals from this object?

I'm looking through old issues now, I thought I saw one about this - but maybe soon I'll look for some help!

**Comment by jbculbertson** [comment]
just overheard Ben talking with Corey - data.games.length returns # of games played, which is a stat!  MVP!  (I'll continue looking into better stats too)

**Comment by scottyscripts** [comment]
So you are getting back an array of objects. Each object is representing a game. Since it is an array, we can use `.length` to tell how many game objects are in said array. If you wanted other information from those games, perhaps you could iterate through your array of game objects and do something for each game object

**Comment by jbculbertson** [comment]
closing this for now.  thanks for the tips
